# Generated by Django 2.1.1 on 2018-09-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_gamemove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='owning_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
