# Generated by Django 2.1.1 on 2018-09-05 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0003_auto_20180905_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='minemap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
