# Generated by Django 2.1.1 on 2018-09-06 00:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0004_auto_20180905_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='flagmap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='openmap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
