# Generated by Django 2.1.1 on 2018-09-06 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0006_auto_20180906_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='flagmap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='openmap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
