# Generated by Django 2.1.1 on 2018-09-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0007_auto_20180906_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game_type',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('hexagonal', 'Hexagonal')], max_length=100),
        ),
    ]
